# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

# Comment the next line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!

# ignore all warnings from all pods
inhibit_all_warnings!

def base_pods
    # Pods for RxSwiftVenezuela
    #  pod 'Moya/RxSwift', '~> 11.0'
    #  pod 'Moya', '~> 11.0'
    #  pod 'RxSwift', '~> 4.0'
    #  pod 'RxCocoa', '~> 4.0'
    pod 'SwiftLint'
    #  pod 'SnapKit', '~> 4.0.0'
    #  pod 'AlamofireObjectMapper'
    #  pod 'ObjectMapper'
    #  pod 'IQKeyboardManagerSwift', '~> 6.1.1'
    #  pod 'R.swift', '~> 4.0.0'
    #  pod 'SkeletonView', '~> 1.2.3'
    #  pod 'Toast-Swift', '~> 3.0.1'
    #  pod 'NVActivityIndicatorView', '~> 4.3.0'
    #  pod 'Validator', '~>  3.0.2'
    #  pod 'AppCenter', '~> 1.8.0'
    #  pod 'MIBadgeButton-Swift', :git => 'https://github.com/mustafaibrahim989/MIBadgeButton-Swift.git', :branch => 'master'
    #  pod 'RealmSwift'
    #
    #  pod 'FacebookCore'
    #  pod 'FacebookLogin'
    #  pod 'FacebookShare'
    #  pod 'JVFloatLabeledTextField'
    #  pod 'PopupDialog', '~> 0.8'
    #  pod 'SearchTextField', '~> 1.2.1'
    #  pod 'GooglePlaces', '= 2.7.0'
    #  pod 'GooglePlacePicker', '= 2.7.0'
    #  pod 'GoogleMaps', '= 2.7.0'
    
end

target 'RxSwiftVenezuela' do
    inherit! :search_paths
    use_frameworks!
    base_pods

    abstract_target 'Tests' do
        target "RxSwiftVenezuelaTests"
        target "RxSwiftVenezuelaUITests"
#        pod 'Moya', '~> 11.0'
#        pod 'RxBlocking', '~> 4.0'
#        pod 'RxTest', '~> 4.0'
#        #    pod 'Quick', '~> 1.3.1'
#        pod 'Nimble', '~> 7.1.3'
    end
end
